import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ModalContextProvider } from "@/context/modal.context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="relative">
        <ModalContextProvider>
          {children}
          <div id="portal"></div>
        </ModalContextProvider>
      </body>
    </html>
  );
}
